apiVersion: v1
kind: Service
metadata:
  name: molen-api
  namespace: molen
  labels:
    app: molen-api
    component: backend
spec:
  type: ClusterIP
  selector:
    app: molen-api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None
