/**
 * Type definitions for Molen Fraud-Ops Platform
 * Note: These types will eventually be auto-generated by Rust backend (specta)
 * Keep them strictly isolated here for future-proofing
 */

/**
 * Represents a financial transaction
 */
export interface Transaction {
  id: string;
  user_id: string;
  amount: number;
  currency: string;
  merchant: string;
  timestamp: string;
  ip_address?: string;
  device_id?: string;
  country?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Decision enum for fraud detection results
 */
export const Decision = {
  PASS: 'PASS',
  FLAG: 'FLAG',
  BLOCK: 'BLOCK',
} as const;

export type Decision = (typeof Decision)[keyof typeof Decision];

/**
 * Result of fraud inference/detection
 */
export interface InferenceResult {
  decision: Decision;
  fraud_score: number;
  confidence: number;
  reason: string;
  rule_triggered?: string;
  model_version?: string;
  timestamp: string;
}

/**
 * Node types in the graph
 */
export type NodeType = 
  | 'input' 
  | 'logic_gate' 
  | 'velocity_check' 
  | 'ml_model' 
  | 'enrichment'
  | 'output';

/**
 * Configuration data for different node types
 */
export interface MolenNodeData extends Record<string, unknown> {
  label: string;
  nodeType: NodeType;
  
  // Logic Gate configuration
  threshold?: number;
  operator?: 'gt' | 'lt' | 'eq' | 'gte' | 'lte';
  field?: string;
  
  // Velocity Check configuration
  timeWindow?: number; // in seconds
  maxCount?: number;
  groupBy?: string;
  
  // ML Model configuration
  modelVersion?: string;
  modelType?: 'xgboost' | 'tensorflow' | 'pytorch';
  
  // Enrichment configuration
  enrichmentType?: 'user_history' | 'merchant_data' | 'device_fingerprint';
  
  // General
  description?: string;
  config?: Record<string, unknown>;
}

/**
 * Execution state for node testing
 */
export type ExecutionState = 'idle' | 'testing' | 'success' | 'error';

/**
 * Test result for a single node
 */
export interface TestResult {
  nodeId: string;
  success: boolean;
  result?: InferenceResult;
  error?: string;
  executionTime?: number;
  timestamp: string;
}

/**
 * Deployment environment
 */
export type DeploymentEnv = 'dev' | 'shadow' | 'prod';

/**
 * Deployment result
 */
export interface DeploymentResult {
  status: string;
  deploymentId: string;
  environment: DeploymentEnv;
  timestamp: string;
  message?: string;
}
