global:
  mode: omnibus
api:
  image:
    repository: ghcr.io/sayyidyofa/molen-api
    tag: latest
  replicas: 3
worker:
  image:
    repository: ghcr.io/sayyidyofa/molen-worker
    tag: latest
  replicas: 5
frontend:
  image:
    repository: ghcr.io/sayyidyofa/molen-frontend
    tag: latest
  replicas: 2
