apiVersion: apps/v1
kind: Deployment
metadata:
  name: molen-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: molen-api
  template:
    metadata:
      labels:
        app: molen-api
    spec:
      containers:
      - name: api
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        ports:
        - containerPort: 3000
