apiVersion: apps/v1
kind: Deployment
metadata:
  name: molen-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: molen-worker
  template:
    metadata:
      labels:
        app: molen-worker
    spec:
      containers:
      - name: worker
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
